version: '3.9'
services:
  database:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    command: [ "redis-server","/etc/redis/redis.conf" ]
    restart: always
    environment:
      REDIS_PASSWORD: redis-password
    ports:
      - '6380:6380'
    volumes:
      - redis:/data
      - ./redis/conf:/etc/redis/
volumes:
  postgres:
  redis:
    driver: local